language: ruby
rvm:
  - 2.5.0
node_js: 8.0.0
cache:
  - bundler
  - yarn
addons:
  postgresql: 9.6
env:
  global:
    - RAILS_ENV=test
    - DATABASE_URL=postgresql://postgres@localhost/fortuna_test
before_script:
  - psql -c 'create database fortuna_test;' -U postgres
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
script:
  - bundle exec rubocop
  - bundle exec rails db:migrate
  - bundle exec rake test
