- start: "0000-01-01"
  end: "2013-12-31"
  value: 18780
- start: "2014-01-01"
  end: "2014-06-30"
  value: 19047
- start: "2014-07-01"
  end: "2016-09-30"
  value: 19273
- start: "2016-10-01"
  end: "2016-12-31"
  value: 20008
- start: "2017-01-01"
  end: "2017-12-31"
  value: 21009
- start: "2018-01-01"
  end: "2018-12-31"
  value: 22000
- start: "2019-01-01"
  end: "2019-12-31"
  value: 23100
- start: "2020-01-01"
  end: "2020-12-31"
  value: 23800
- start: "2021-01-01"
  end: "2021-12-31"
  value: 24000
- start: "2022-01-01"
  end: "2022-12-31"
  value: 25250
- start: "2023-01-01"
  end: "2023-12-31"
  value: 26400
- start: "2024-01-01"
  end: "2024-12-31"
  value: 27470
- start: "2025-01-01"
  end: "infinity"
  value: 28590
